// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "project/internal/app/pkg/dto"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateUserBooking provides a mock function with given fields: user
func (_m *Service) CreateUserBooking(user dto.BookingDetails) (dto.BookingDetails, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserBooking")
	}

	var r0 dto.BookingDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.BookingDetails) (dto.BookingDetails, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(dto.BookingDetails) dto.BookingDetails); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(dto.BookingDetails)
	}

	if rf, ok := ret.Get(1).(func(dto.BookingDetails) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSlots provides a mock function with given fields: ctx
func (_m *Service) GetSlots(ctx context.Context) ([]dto.SlotResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSlots")
	}

	var r0 []dto.SlotResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dto.SlotResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dto.SlotResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.SlotResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
